version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  condomanager.api:
    image: ${DOCKER_REGISTRY-}condomanagerapi
    build:
      context: .
      dockerfile: CondoManager.Api/Dockerfile
    depends_on:
      - "postgres_image"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=condodb;username=condouser;password=marcospaulo"
    networks:
      - dockerapi-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "condouser"
      POSTGRES_PASSWORD: "marcospaulo"
      POSTGRES_DB: "condodb"
    networks:
      - dockerapi-dev
volumes:
  db_volume:
         
    
     